import { INodeProperties } from 'n8n-workflow';

export const ticketOperations: INodeProperties[] = [
    {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['ticket'] } },
        options: [
            {
                name: 'Get All (mit Filtern)',
                value: 'getAll',
                description: 'Mehrere Tickets abrufen – mit Status, Priorität, Gruppe, Datum etc.',
                action: 'Get all tickets',
            },
            {
                name: 'Get (einzeln)',
                value: 'get',
                description: 'Ein einzelnes Ticket per ID abrufen',
                action: 'Get a ticket',
            },
            {
                name: 'Suchen',
                value: 'search',
                description: 'Tickets per Volltext, Telefonnummer, Ticketnummer oder Titel suchen',
                action: 'Search tickets',
            },
            {
                name: 'Erstellen',
                value: 'create',
                description: 'Neues Ticket anlegen',
                action: 'Create a ticket',
            },
            {
                name: 'Aktualisieren',
                value: 'update',
                description: 'Bestehendes Ticket aktualisieren',
                action: 'Update a ticket',
            },
            {
                name: 'Löschen',
                value: 'delete',
                description: 'Ticket löschen',
                action: 'Delete a ticket',
            },
        ],
        default: 'getAll',
    },
];

export const ticketFields: INodeProperties[] = [
    // ─── GET (single) / UPDATE / DELETE ─────────────────────────────────────────
    {
        displayName: 'Ticket-ID',
        name: 'ticketId',
        type: 'number',
        required: true,
        displayOptions: {
            show: { resource: ['ticket'], operation: ['get', 'update', 'delete'] },
        },
        default: 0,
        description: 'Eindeutige numerische ID des Tickets',
    },

    // ─── GET ALL ─────────────────────────────────────────────────────────────────
    {
        displayName: 'Limit',
        name: 'limit',
        type: 'number',
        displayOptions: { show: { resource: ['ticket'], operation: ['getAll'] } },
        typeOptions: { minValue: 1, maxValue: 500 },
        default: 25,
        description: 'Maximale Anzahl zurückzugebender Tickets',
    },
    {
        displayName: 'Sortieren nach',
        name: 'sortBy',
        type: 'options',
        displayOptions: { show: { resource: ['ticket'], operation: ['getAll'] } },
        options: [
            { name: 'Erstellt am', value: 'created_at' },
            { name: 'Aktualisiert am', value: 'updated_at' },
            { name: 'ID', value: 'id' },
            { name: 'Titel', value: 'title' },
            { name: 'Priorität', value: 'priority' },
        ],
        default: 'created_at',
    },
    {
        displayName: 'Reihenfolge',
        name: 'sortOrder',
        type: 'options',
        displayOptions: { show: { resource: ['ticket'], operation: ['getAll'] } },
        options: [
            { name: 'Absteigend (neueste zuerst)', value: 'desc' },
            { name: 'Aufsteigend (älteste zuerst)', value: 'asc' },
        ],
        default: 'desc',
    },
    {
        displayName: 'Filter',
        name: 'filters',
        type: 'collection',
        placeholder: 'Filter hinzufügen',
        default: {},
        displayOptions: { show: { resource: ['ticket'], operation: ['getAll'] } },
        options: [
            {
                displayName: 'Status',
                name: 'status',
                type: 'multiOptions',
                options: [
                    { name: 'Neu', value: 'new' },
                    { name: 'Offen', value: 'open' },
                    { name: 'Ausstehend – Erinnerung', value: 'pending reminder' },
                    { name: 'Ausstehend – Schließen', value: 'pending close' },
                    { name: 'Geschlossen', value: 'closed' },
                    { name: 'Zusammengeführt', value: 'merged' },
                ],
                default: [],
                description: 'Nur Tickets mit diesen Status',
            },
            {
                displayName: 'Priorität',
                name: 'priority',
                type: 'multiOptions',
                options: [
                    { name: 'Niedrig (1)', value: '1 low' },
                    { name: 'Normal (2)', value: '2 normal' },
                    { name: 'Hoch (3)', value: '3 high' },
                ],
                default: [],
                description: 'Nur Tickets mit diesen Prioritäten',
            },
            {
                displayName: 'Gruppe / Team',
                name: 'group',
                type: 'string',
                default: '',
                placeholder: 'z. B. Support',
                description: 'Exakter Gruppenname in Zammad',
            },
            {
                displayName: 'Zugewiesener Agent (Owner)',
                name: 'owner',
                type: 'string',
                default: '',
                placeholder: 'z. B. agent@firma.de',
                description: 'E-Mail oder Login des zugewiesenen Agenten',
            },
            {
                displayName: 'Kunde (Customer)',
                name: 'customer',
                type: 'string',
                default: '',
                placeholder: 'z. B. kunde@firma.de',
                description: 'E-Mail oder Login des Kunden',
            },
            {
                displayName: 'Organisation',
                name: 'organization',
                type: 'string',
                default: '',
                placeholder: 'z. B. ACME GmbH',
                description: 'Name der Organisation',
            },
            {
                displayName: 'Erstellt nach (Datum)',
                name: 'createdAfter',
                type: 'dateTime',
                default: '',
                description: 'Nur Tickets, die nach diesem Zeitpunkt erstellt wurden',
            },
            {
                displayName: 'Aktualisiert nach (Datum)',
                name: 'updatedAfter',
                type: 'dateTime',
                default: '',
                description: 'Nur Tickets, die nach diesem Zeitpunkt aktualisiert wurden',
            },
            {
                displayName: 'Eigene Suchabfrage (Elasticsearch)',
                name: 'customQuery',
                type: 'string',
                default: '',
                placeholder: 'z. B. title:Fehler AND tag:dringend',
                description:
                    'Rohe Zammad/Elasticsearch-Abfrage – wird mit allen anderen Filtern per AND verknüpft',
            },
        ],
    },

    // ─── SEARCH ──────────────────────────────────────────────────────────────────
    {
        displayName: 'Suchbegriff',
        name: 'query',
        type: 'string',
        required: true,
        displayOptions: { show: { resource: ['ticket'], operation: ['search'] } },
        default: '',
        placeholder: 'z. B. +4912345678 oder Anmeldeproblem',
        description: 'Suchbegriff – Freitext, Telefonnummer, Ticketnummer etc.',
    },
    {
        displayName: 'Suchen in',
        name: 'searchIn',
        type: 'options',
        displayOptions: { show: { resource: ['ticket'], operation: ['search'] } },
        options: [
            { name: 'Überall (Volltext)', value: 'fulltext' },
            { name: 'Telefonnummer des Kunden', value: 'phone' },
            { name: 'Ticketnummer', value: 'number' },
            { name: 'Titel / Betreff', value: 'title' },
        ],
        default: 'fulltext',
        description: 'In welchem Feld gesucht werden soll',
    },
    {
        displayName: 'Limit',
        name: 'searchLimit',
        type: 'number',
        displayOptions: { show: { resource: ['ticket'], operation: ['search'] } },
        typeOptions: { minValue: 1, maxValue: 500 },
        default: 25,
        description: 'Maximale Trefferzahl',
    },

    // ─── CREATE ──────────────────────────────────────────────────────────────────
    {
        displayName: 'Titel',
        name: 'title',
        type: 'string',
        required: true,
        displayOptions: { show: { resource: ['ticket'], operation: ['create'] } },
        default: '',
        description: 'Betreff / Titel des Tickets',
    },
    {
        displayName: 'Gruppe',
        name: 'createGroup',
        type: 'string',
        required: true,
        displayOptions: { show: { resource: ['ticket'], operation: ['create'] } },
        default: 'Users',
        placeholder: 'z. B. Support',
        description: 'Zammad-Gruppe, der das Ticket zugeordnet wird',
    },
    {
        displayName: 'Kunden-E-Mail',
        name: 'customerEmail',
        type: 'string',
        required: true,
        displayOptions: { show: { resource: ['ticket'], operation: ['create'] } },
        default: '',
        placeholder: 'kunde@firma.de',
        description: 'E-Mail-Adresse des Kunden (Ersteller des Tickets)',
    },
    {
        displayName: 'Nachricht / Artikeltext',
        name: 'articleBody',
        type: 'string',
        required: true,
        typeOptions: { rows: 5 },
        displayOptions: { show: { resource: ['ticket'], operation: ['create'] } },
        default: '',
        description: 'Text des ersten Artikels (die eigentliche Ticketnachricht)',
    },
    {
        displayName: 'Weitere Felder',
        name: 'additionalFields',
        type: 'collection',
        placeholder: 'Feld hinzufügen',
        default: {},
        displayOptions: { show: { resource: ['ticket'], operation: ['create'] } },
        options: [
            {
                displayName: 'Status',
                name: 'state',
                type: 'options',
                options: [
                    { name: 'Neu', value: 'new' },
                    { name: 'Offen', value: 'open' },
                    { name: 'Ausstehend – Erinnerung', value: 'pending reminder' },
                    { name: 'Ausstehend – Schließen', value: 'pending close' },
                    { name: 'Geschlossen', value: 'closed' },
                ],
                default: 'new',
            },
            {
                displayName: 'Priorität',
                name: 'priority',
                type: 'options',
                options: [
                    { name: 'Niedrig', value: '1 low' },
                    { name: 'Normal', value: '2 normal' },
                    { name: 'Hoch', value: '3 high' },
                ],
                default: '2 normal',
            },
            {
                displayName: 'Owner (Agent-Login)',
                name: 'owner',
                type: 'string',
                default: '',
                description: 'Login-Name des zugewiesenen Agenten',
            },
            {
                displayName: 'Artikel-Betreff',
                name: 'articleSubject',
                type: 'string',
                default: '',
                description: 'Betreff des ersten Artikels (Standard: Tickettitel)',
            },
            {
                displayName: 'Artikel-Typ',
                name: 'articleType',
                type: 'options',
                options: [
                    { name: 'Notiz', value: 'note' },
                    { name: 'E-Mail', value: 'email' },
                    { name: 'Telefon', value: 'phone' },
                    { name: 'Web', value: 'web' },
                ],
                default: 'note',
            },
            {
                displayName: 'Inhaltstyp',
                name: 'contentType',
                type: 'options',
                options: [
                    { name: 'Klartext (text/plain)', value: 'text/plain' },
                    { name: 'HTML (text/html)', value: 'text/html' },
                ],
                default: 'text/plain',
            },
            {
                displayName: 'Interne Notiz',
                name: 'internal',
                type: 'boolean',
                default: false,
                description: 'Wenn aktiv, ist der Artikel nur für Agenten sichtbar',
            },
        ],
    },

    // ─── UPDATE ──────────────────────────────────────────────────────────────────
    {
        displayName: 'Zu aktualisierende Felder',
        name: 'updateFields',
        type: 'collection',
        placeholder: 'Feld hinzufügen',
        default: {},
        displayOptions: { show: { resource: ['ticket'], operation: ['update'] } },
        options: [
            {
                displayName: 'Titel',
                name: 'title',
                type: 'string',
                default: '',
            },
            {
                displayName: 'Gruppe',
                name: 'group',
                type: 'string',
                default: '',
                placeholder: 'z. B. Support',
            },
            {
                displayName: 'Status',
                name: 'state',
                type: 'options',
                options: [
                    { name: 'Neu', value: 'new' },
                    { name: 'Offen', value: 'open' },
                    { name: 'Ausstehend – Erinnerung', value: 'pending reminder' },
                    { name: 'Ausstehend – Schließen', value: 'pending close' },
                    { name: 'Geschlossen', value: 'closed' },
                ],
                default: 'open',
            },
            {
                displayName: 'Priorität',
                name: 'priority',
                type: 'options',
                options: [
                    { name: 'Niedrig', value: '1 low' },
                    { name: 'Normal', value: '2 normal' },
                    { name: 'Hoch', value: '3 high' },
                ],
                default: '2 normal',
            },
            {
                displayName: 'Owner (Agent-Login)',
                name: 'owner',
                type: 'string',
                default: '',
            },
            {
                displayName: 'Kunde (E-Mail)',
                name: 'customer',
                type: 'string',
                default: '',
            },
        ],
    },
];
