import { INodeProperties } from 'n8n-workflow';

export const ticketOperations: INodeProperties[] = [
    {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['ticket'] } },
        options: [
            {
                name: 'Get All (mit Filtern)',
                value: 'getAll',
                description: 'Mehrere Tickets abrufen – mit Status, Priorität, Gruppe, Datum etc. (kein Elasticsearch erforderlich)',
                action: 'Get all tickets',
            },
            {
                name: 'Get (einzeln)',
                value: 'get',
                description: 'Ein einzelnes Ticket per ID abrufen',
                action: 'Get a ticket',
            },
            {
                name: 'Suchen',
                value: 'search',
                description: 'Tickets per Volltext, Telefonnummer, Ticketnummer oder Titel suchen',
                action: 'Search tickets',
            },
            {
                name: 'Erstellen',
                value: 'create',
                description: 'Neues Ticket anlegen',
                action: 'Create a ticket',
            },
            {
                name: 'Aktualisieren',
                value: 'update',
                description: 'Bestehendes Ticket aktualisieren',
                action: 'Update a ticket',
            },
            {
                name: 'Löschen',
                value: 'delete',
                description: 'Ticket löschen',
                action: 'Delete a ticket',
            },
        ],
        default: 'getAll',
    },
];

// ─── Custom Fields dieses Zammad-Systems ─────────────────────────────────────
// (aus /api/v1/object_manager_attributes?object=Ticket, active+editable)
const ticketCustomFields: INodeProperties[] = [
    // ── Auswahl-Felder ───────────────────────────────────────────────────────
    {
        displayName: 'Ticket Art',
        name: 'tickettype',
        type: 'options',
        options: [
            { name: '– nicht gesetzt –', value: '' },
            { name: 'Altes Ticket', value: 'Altes Ticket' },
            { name: 'Intern Easy', value: 'Intern Easy' },
            { name: 'Intern IT', value: 'Intern IT' },
            { name: 'intern Allgemein', value: 'intern Allgemein' },
            { name: 'intern Zeiterfassung', value: 'intern Zeiterfassung' },
            { name: 'Kunde', value: 'Kunde' },
            { name: 'Partner', value: 'Partner' },
        ],
        default: '',
    },
    {
        displayName: 'Produktwahl',
        name: 'produktwahl',
        type: 'options',
        options: [
            { name: '– nicht gesetzt –', value: '' },
            { name: 'Druck & Kopier Systeme', value: 'mfp' },
            { name: 'indexCreator', value: 'sbic' },
            { name: 'Kanzlei', value: 'sbk' },
            { name: 'Mandant connect', value: 'sbmcii' },
            { name: 'Mobile App', value: 'sbapp' },
            { name: 'nicht Produkt bezogen', value: 'andere' },
        ],
        default: '',
    },
    {
        displayName: 'Prio (Custom)',
        name: 'prio',
        type: 'options',
        options: [
            { name: '– nicht gesetzt –', value: '' },
            { name: 'Hoch', value: 'Hoch' },
            { name: 'Niedrig', value: 'Niedrig' },
            { name: 'Normal', value: 'Normal' },
            { name: 'ShowStopper', value: 'ShowStopper' },
            { name: 'Techniker vor Ort', value: 'Techniker vor Ort' },
        ],
        default: '',
    },
    {
        displayName: 'Typ (Custom)',
        name: 'type',
        type: 'options',
        options: [
            { name: '– nicht gesetzt –', value: '' },
            { name: 'Allgemein', value: 'Allgemein' },
            { name: 'Andere', value: 'Andere' },
            { name: 'Hardware', value: 'Hardware' },
            { name: 'Lizenz', value: 'Lizenz' },
            { name: 'Mitarbeiter neuanlage', value: 'Mitarbeiter' },
            { name: 'Software', value: 'Software' },
            { name: 'Transportschaden', value: 'Transportschaden' },
            { name: 'Verbrauchsmaterial', value: 'Verbrauchsmaterial' },
            { name: 'Zählerstand', value: 'Zählerstand' },
        ],
        default: '',
    },
    {
        displayName: 'Supportart',
        name: 'supportart',
        type: 'options',
        options: [
            { name: '– nicht gesetzt –', value: '' },
            { name: 'Remote', value: 'Remote' },
            { name: 'Vorort', value: 'Vorort' },
        ],
        default: '',
    },
    {
        displayName: 'Betroffener Partner',
        name: 'betroffenerpartner',
        type: 'options',
        options: [
            { name: '– nicht gesetzt –', value: '' },
            { name: 'Abenhausen Büro- und Datentechnik GmbH', value: 'abenhausen' },
            { name: 'ACI EDV – Systemhaus GmbH', value: 'aci' },
            { name: 'ACT - Angewandte Computer Technik GmbH', value: 'act' },
            { name: 'Braun & Paul IT GmbH', value: 'bup' },
            { name: 'Brunner & Schmidt Datentechnik GmbH', value: 'bus' },
            { name: 'C&P Capeletti & Perl Gesellschaft für Datentechnik mbH', value: 'cup' },
            { name: 'conNect Organisation und Netzwerk GmbH', value: 'connect' },
            { name: 'CSW GmbH', value: 'csw' },
            { name: 'Dipl. Inform. Christian Naumann', value: 'naumann' },
            { name: 'dns Datentechnik, Netzwerk und Systemhaus GmbH', value: 'dns' },
            { name: 'Dr. Evert & Dr. Sehan GmbH (Müritz Comp)', value: 'Müritz' },
            { name: 'EDVA GmbH', value: 'edva' },
            { name: 'ERHARDT BÜROWELT GmbH', value: 'erhardt' },
            { name: 'Förster IT-Dienstleistungen GmbH', value: 'foerster' },
            { name: 'Großbecker & Nordt Bürotechnik Handels GmbH', value: 'gun' },
            { name: 'Haas & Letze GmbH', value: 'haasuletze' },
            { name: 'ITM GmbH', value: 'itm' },
            { name: 'microPLAN IT-Systemhaus GmbH', value: 'microplan' },
            { name: 'msystems IT-Solutions GmbH', value: 'msystems' },
            { name: 'netgo group GmbH', value: 'netgo' },
            { name: 'netgo tax GmbH (Ehmalig Nitsche)', value: 'nitsche' },
            { name: 'NetPlans GmbH', value: 'netplans' },
            { name: 'page one GmbH', value: 'pageone' },
            { name: 'Paul Sonnabend Büro- und Datentechnik GmbH & Co. KG', value: 'sonnabend' },
            { name: 'Schuster & Walther IT-Business GmbH', value: 'schuwa' },
            { name: 'WIZARD Computersysteme GmbH', value: 'wizard' },
        ],
        default: '',
    },
    {
        displayName: 'Ticketqualität',
        name: 'ticketqualitart',
        type: 'options',
        options: [
            { name: '– nicht gesetzt –', value: '' },
            { name: 'Gut', value: 'gut' },
            { name: 'Mittelmäßig', value: 'mittelmaeßig' },
            { name: 'Perfekt', value: 'perfekt' },
            { name: 'Schlecht', value: 'schlecht' },
        ],
        default: '',
    },
    {
        displayName: 'E-Mail Text Anmeldung',
        name: 'e_mail_text_anmeldung',
        type: 'options',
        options: [
            { name: '– nicht gesetzt –', value: '' },
            { name: 'Ja', value: 'Ja' },
            { name: 'Nein', value: 'Nein' },
        ],
        default: '',
    },
    {
        displayName: 'KI-Ticket Infos vollständig',
        name: 'kiticketinfo',
        type: 'options',
        options: [
            { name: '– nicht gesetzt –', value: '' },
            { name: 'Ja (alle Infos vorhanden)', value: 'Alle notwendigen Ticket Informationen' },
            { name: 'Nein (Infos unvollständig)', value: 'Ticketinformationen nicht ausreichend für Bearbeitung' },
        ],
        default: '',
    },
    {
        displayName: 'Fonio Ticket',
        name: 'fonio_ticket',
        type: 'options',
        options: [
            { name: '– nicht gesetzt –', value: '' },
            { name: 'Ja', value: 'Ja' },
            { name: 'Nein', value: 'Nein' },
        ],
        default: '',
    },
    // ── Text-Felder ──────────────────────────────────────────────────────────
    {
        displayName: 'Alternativer Ansprechpartner',
        name: 'alt_ansprechpartner',
        type: 'string',
        default: '',
    },
    {
        displayName: 'Ansprechpartner: Endkunde',
        name: 'ansprechpartner',
        type: 'string',
        default: '',
    },
    {
        displayName: 'E-Mail: Ansprechpartner',
        name: 'mail',
        type: 'string',
        default: '',
    },
    {
        displayName: 'E-Mail: Endkunde',
        name: 'mail_endkunde',
        type: 'string',
        default: '',
    },
    {
        displayName: 'Endkunde',
        name: 'kd',
        type: 'string',
        default: '',
    },
    {
        displayName: 'Hinweis',
        name: 'hinweis',
        type: 'string',
        default: '',
    },
    {
        displayName: 'Installations-Datum',
        name: 'installations_datum',
        type: 'string',
        default: '',
        placeholder: 'YYYY-MM-DD',
    },
    {
        displayName: 'Notiz (Zammad Custom Field)',
        name: 'notiz',
        type: 'string',
        default: '',
        description: 'Zammad Custom Field „notiz" – nicht zu verwechseln mit dem Artikel-Kommentar oben',
    },
    {
        displayName: 'Seriennummer (Hardware/Software)',
        name: 'sn',
        type: 'string',
        default: '',
    },
    {
        displayName: 'Standort',
        name: 'standort',
        type: 'string',
        default: '',
    },
    {
        displayName: 'Telefon: Endkunde',
        name: 'tel',
        type: 'string',
        default: '',
    },
    {
        displayName: 'Telefon: Partner',
        name: 'telpart',
        type: 'string',
        default: '',
    },
    {
        displayName: 'Telefonnummer (Endkunde)',
        name: 'telefonnummer_endkunde',
        type: 'string',
        default: '',
    },
    {
        displayName: 'Unterbrochen',
        name: 'unterbrochen',
        type: 'string',
        default: '',
    },
    // ── KI-Felder ────────────────────────────────────────────────────────────
    {
        displayName: 'KI-Priorisierung',
        name: 'ki_priorisierung',
        type: 'boolean',
        default: false,
        description: 'Gibt an ob dieses Ticket von der KI priorisiert wurde',
    },
    {
        displayName: 'KI-Training',
        name: 'ki_training',
        type: 'boolean',
        default: false,
        description: 'Gibt an ob dieses Ticket als KI-Trainingsdaten markiert ist',
    },
];

export const ticketFields: INodeProperties[] = [
    // ─── GET (single) / UPDATE / DELETE ─────────────────────────────────────────
    {
        displayName: 'Ticket-ID',
        name: 'ticketId',
        type: 'number',
        required: true,
        displayOptions: {
            show: { resource: ['ticket'], operation: ['get', 'update', 'delete'] },
        },
        default: 0,
        description: 'Eindeutige numerische ID des Tickets',
    },

    // ─── GET ALL ─────────────────────────────────────────────────────────────────
    {
        displayName: 'Limit',
        name: 'limit',
        type: 'number',
        displayOptions: { show: { resource: ['ticket'], operation: ['getAll'] } },
        typeOptions: { minValue: 1, maxValue: 500 },
        default: 25,
        description: 'Maximale Anzahl zurückzugebender Tickets',
    },
    {
        displayName: 'Sortieren nach',
        name: 'sortBy',
        type: 'options',
        displayOptions: { show: { resource: ['ticket'], operation: ['getAll'] } },
        options: [
            { name: 'Erstellt am', value: 'created_at' },
            { name: 'Aktualisiert am', value: 'updated_at' },
            { name: 'ID', value: 'id' },
            { name: 'Titel', value: 'title' },
            { name: 'Priorität', value: 'priority' },
        ],
        default: 'created_at',
    },
    {
        displayName: 'Reihenfolge',
        name: 'sortOrder',
        type: 'options',
        displayOptions: { show: { resource: ['ticket'], operation: ['getAll'] } },
        options: [
            { name: 'Absteigend (neueste zuerst)', value: 'desc' },
            { name: 'Aufsteigend (älteste zuerst)', value: 'asc' },
        ],
        default: 'desc',
    },
    {
        displayName: 'Filter',
        name: 'filters',
        type: 'collection',
        placeholder: 'Filter hinzufügen',
        default: {},
        displayOptions: { show: { resource: ['ticket'], operation: ['getAll'] } },
        options: [
            {
                displayName: 'Status',
                name: 'status',
                type: 'multiOptions',
                options: [
                    { name: '01 Auftrag erfasst', value: '01 Auftrag erfasst' },
                    { name: '01.5 An Zuständigen weitergegeben', value: '01.5 An Zuständigen weitergegeben' },
                    { name: '02 in Bearbeitung', value: '02 in Bearbeitung' },
                    { name: '03 Unterbrochen', value: '03 Unterbrochen' },
                    { name: '04 geschlossen', value: '04 geschlossen' },
                    { name: '04 geschlossen (ohne Meldung)', value: '04 geschlossen (ohne Meldung)' },
                    { name: 'Abholung beauftragt', value: 'Abholung beauftragt' },
                    { name: 'Angebot Vertrieb', value: 'Angebot Vertrieb' },
                    { name: 'Datenverarbeitung (Zählerstände)', value: 'Datenverarbeitung (Zählerstände)' },
                    { name: 'fürs Order Team', value: 'fürs Order Team' },
                    { name: 'in Entwicklung', value: 'in Entwicklung' },
                    { name: 'Infos fehlen', value: 'Infos fehlen' },
                    { name: 'KVA erstellt', value: 'KVA erstellt' },
                    { name: 'merged', value: 'merged' },
                    { name: 'open', value: 'open' },
                    { name: 'pending close', value: 'pending close' },
                    { name: 'Service (Extern)', value: 'Service (Extern)' },
                    { name: 'Techniker geplant', value: 'Techniker geplant' },
                    { name: 'Termin vereinbart', value: 'Termin vereinbart' },
                    { name: 'Ticket berechnen', value: 'Ticket berechnen' },
                    { name: 'Warte auf Rückmeldung', value: 'Warte auf Rückmeldung' },
                    { name: 'warten auf Schließen (ohne Meldung)', value: 'warten auf Schließen (ohne Meldung)' },
                    { name: 'Zammad KI', value: 'Zammad KI' },
                ],
                default: [],
                description: 'Nur Tickets mit diesen Status (exakter Namensvergleich per Teilstring)',
            },
            {
                displayName: 'Status ausschließen',
                name: 'excludeStatus',
                type: 'multiOptions',
                options: [
                    { name: '01 Auftrag erfasst', value: '01 Auftrag erfasst' },
                    { name: '01.5 An Zuständigen weitergegeben', value: '01.5 An Zuständigen weitergegeben' },
                    { name: '02 in Bearbeitung', value: '02 in Bearbeitung' },
                    { name: '03 Unterbrochen', value: '03 Unterbrochen' },
                    { name: '04 geschlossen', value: '04 geschlossen' },
                    { name: '04 geschlossen (ohne Meldung)', value: '04 geschlossen (ohne Meldung)' },
                    { name: 'Abholung beauftragt', value: 'Abholung beauftragt' },
                    { name: 'Angebot Vertrieb', value: 'Angebot Vertrieb' },
                    { name: 'Datenverarbeitung (Zählerstände)', value: 'Datenverarbeitung (Zählerstände)' },
                    { name: 'fürs Order Team', value: 'fürs Order Team' },
                    { name: 'in Entwicklung', value: 'in Entwicklung' },
                    { name: 'Infos fehlen', value: 'Infos fehlen' },
                    { name: 'KVA erstellt', value: 'KVA erstellt' },
                    { name: 'merged', value: 'merged' },
                    { name: 'open', value: 'open' },
                    { name: 'pending close', value: 'pending close' },
                    { name: 'Service (Extern)', value: 'Service (Extern)' },
                    { name: 'Techniker geplant', value: 'Techniker geplant' },
                    { name: 'Termin vereinbart', value: 'Termin vereinbart' },
                    { name: 'Ticket berechnen', value: 'Ticket berechnen' },
                    { name: 'Warte auf Rückmeldung', value: 'Warte auf Rückmeldung' },
                    { name: 'warten auf Schließen (ohne Meldung)', value: 'warten auf Schließen (ohne Meldung)' },
                    { name: 'Zammad KI', value: 'Zammad KI' },
                ],
                default: [],
                description: 'Tickets mit diesen Status werden herausgefiltert (Ausschluss)',
            },
            {
                displayName: 'Priorität',
                name: 'priority',
                type: 'multiOptions',
                options: [
                    { name: 'Niedrig', value: 'Niedrig' },
                    { name: 'Normal', value: 'Normal' },
                    { name: 'Hoch', value: 'Hoch' },
                    { name: 'ShowStopper', value: 'ShowStopper' },
                    { name: 'Techniker vor Ort', value: 'Techniker vor Ort' },
                ],
                default: [],
                description: 'Nur Tickets mit diesen Prioritäten',
            },
            {
                displayName: 'Gruppe / Team',
                name: 'group',
                type: 'string',
                default: '',
                placeholder: 'z. B. Support',
                description: 'Exakter Gruppenname in Zammad',
            },
            {
                displayName: 'Zugewiesener Agent (Owner)',
                name: 'owner',
                type: 'string',
                default: '',
                placeholder: 'z. B. agent@firma.de',
                description: 'E-Mail oder Login des zugewiesenen Agenten',
            },
            {
                displayName: 'Kunde (Customer)',
                name: 'customer',
                type: 'string',
                default: '',
                placeholder: 'z. B. kunde@firma.de',
                description: 'E-Mail oder Login des Kunden',
            },
            {
                displayName: 'Organisation',
                name: 'organization',
                type: 'string',
                default: '',
                placeholder: 'z. B. ACME GmbH',
                description: 'Name der Organisation',
            },
            {
                displayName: 'Erstellt nach (Datum)',
                name: 'createdAfter',
                type: 'dateTime',
                default: '',
                description: 'Nur Tickets, die nach diesem Zeitpunkt erstellt wurden',
            },
            {
                displayName: 'Aktualisiert nach (Datum)',
                name: 'updatedAfter',
                type: 'dateTime',
                default: '',
                description: 'Nur Tickets, die nach diesem Zeitpunkt aktualisiert wurden',
            },
        ],
    },

    // ─── SEARCH ──────────────────────────────────────────────────────────────────
    {
        displayName: 'Suchbegriff',
        name: 'query',
        type: 'string',
        required: true,
        displayOptions: { show: { resource: ['ticket'], operation: ['search'] } },
        default: '',
        placeholder: 'z. B. +4912345678 oder Anmeldeproblem',
        description: 'Suchbegriff – Freitext, Telefonnummer, Ticketnummer etc.',
    },
    {
        displayName: 'Suchen in',
        name: 'searchIn',
        type: 'options',
        displayOptions: { show: { resource: ['ticket'], operation: ['search'] } },
        options: [
            { name: 'Überall (Volltext)', value: 'fulltext' },
            { name: 'Telefonnummer des Kunden', value: 'phone' },
            { name: 'Ticketnummer', value: 'number' },
            { name: 'Titel / Betreff', value: 'title' },
        ],
        default: 'fulltext',
        description: 'In welchem Feld gesucht werden soll',
    },
    {
        displayName: 'Limit',
        name: 'searchLimit',
        type: 'number',
        displayOptions: { show: { resource: ['ticket'], operation: ['search'] } },
        typeOptions: { minValue: 1, maxValue: 500 },
        default: 25,
        description: 'Maximale Trefferzahl',
    },
    {
        displayName: 'Suchoptionen',
        name: 'searchOptions',
        type: 'collection',
        placeholder: 'Option hinzufügen',
        default: {},
        displayOptions: { show: { resource: ['ticket'], operation: ['search'] } },
        options: [
            {
                displayName: 'Sortieren nach',
                name: 'sort_by',
                type: 'options',
                options: [
                    { name: 'Erstellt am', value: 'created_at' },
                    { name: 'Aktualisiert am', value: 'updated_at' },
                    { name: 'Ticketnummer', value: 'number' },
                    { name: 'Titel', value: 'title' },
                    { name: 'Status', value: 'state' },
                    { name: 'Priorität', value: 'priority' },
                ],
                default: 'created_at',
                description: 'Elasticsearch-Ergebnis nach diesem Feld sortieren',
            },
            {
                displayName: 'Sortierreihenfolge',
                name: 'order_by',
                type: 'options',
                options: [
                    { name: 'Absteigend (neueste zuerst)', value: 'desc' },
                    { name: 'Aufsteigend (älteste zuerst)', value: 'asc' },
                ],
                default: 'desc',
            },
            // ── Custom Field Filter (Select-Felder) ──────────────────────────────
            {
                displayName: 'Filter: Ticket Art',
                name: 'tickettype',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Altes Ticket', value: 'Altes Ticket' },
                    { name: 'Intern Easy', value: 'Intern Easy' },
                    { name: 'Intern IT', value: 'Intern IT' },
                    { name: 'intern Allgemein', value: 'intern Allgemein' },
                    { name: 'intern Zeiterfassung', value: 'intern Zeiterfassung' },
                    { name: 'Kunde', value: 'Kunde' },
                    { name: 'Partner', value: 'Partner' },
                ],
                default: '',
            },
            {
                displayName: 'Filter: Produktwahl',
                name: 'produktwahl',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Druck & Kopier Systeme', value: 'mfp' },
                    { name: 'indexCreator', value: 'sbic' },
                    { name: 'Kanzlei', value: 'sbk' },
                    { name: 'Mandant connect', value: 'sbmcii' },
                    { name: 'Mobile App', value: 'sbapp' },
                    { name: 'nicht Produkt bezogen', value: 'andere' },
                ],
                default: '',
            },
            {
                displayName: 'Filter: Prio (Custom)',
                name: 'prio',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Hoch', value: 'Hoch' },
                    { name: 'Niedrig', value: 'Niedrig' },
                    { name: 'Normal', value: 'Normal' },
                    { name: 'ShowStopper', value: 'ShowStopper' },
                    { name: 'Techniker vor Ort', value: 'Techniker vor Ort' },
                ],
                default: '',
            },
            {
                displayName: 'Filter: Typ (Custom)',
                name: 'type',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Allgemein', value: 'Allgemein' },
                    { name: 'Andere', value: 'Andere' },
                    { name: 'Hardware', value: 'Hardware' },
                    { name: 'Lizenz', value: 'Lizenz' },
                    { name: 'Mitarbeiter neuanlage', value: 'Mitarbeiter' },
                    { name: 'Software', value: 'Software' },
                    { name: 'Transportschaden', value: 'Transportschaden' },
                    { name: 'Verbrauchsmaterial', value: 'Verbrauchsmaterial' },
                    { name: 'Zählerstand', value: 'Zählerstand' },
                ],
                default: '',
            },
            {
                displayName: 'Filter: Supportart',
                name: 'supportart',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Remote', value: 'Remote' },
                    { name: 'Vorort', value: 'Vorort' },
                ],
                default: '',
            },
            {
                displayName: 'Filter: Betroffener Partner',
                name: 'betroffenerpartner',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Abenhausen Büro- und Datentechnik GmbH', value: 'abenhausen' },
                    { name: 'ACI EDV – Systemhaus GmbH', value: 'aci' },
                    { name: 'ACT - Angewandte Computer Technik GmbH', value: 'act' },
                    { name: 'Braun & Paul IT GmbH', value: 'bup' },
                    { name: 'Brunner & Schmidt Datentechnik GmbH', value: 'bus' },
                    { name: 'C&P Capeletti & Perl Gesellschaft für Datentechnik mbH', value: 'cup' },
                    { name: 'conNect Organisation und Netzwerk GmbH', value: 'connect' },
                    { name: 'CSW GmbH', value: 'csw' },
                    { name: 'Dipl. Inform. Christian Naumann', value: 'naumann' },
                    { name: 'dns Datentechnik, Netzwerk und Systemhaus GmbH', value: 'dns' },
                    { name: 'Dr. Evert & Dr. Sehan GmbH (Müritz Comp)', value: 'Müritz' },
                    { name: 'EDVA GmbH', value: 'edva' },
                    { name: 'ERHARDT BÜROWELT GmbH', value: 'erhardt' },
                    { name: 'Förster IT-Dienstleistungen GmbH', value: 'foerster' },
                    { name: 'Großbecker & Nordt Bürotechnik Handels GmbH', value: 'gun' },
                    { name: 'Haas & Letze GmbH', value: 'haasuletze' },
                    { name: 'ITM GmbH', value: 'itm' },
                    { name: 'microPLAN IT-Systemhaus GmbH', value: 'microplan' },
                    { name: 'msystems IT-Solutions GmbH', value: 'msystems' },
                    { name: 'netgo group GmbH', value: 'netgo' },
                    { name: 'netgo tax GmbH (Ehmalig Nitsche)', value: 'nitsche' },
                    { name: 'NetPlans GmbH', value: 'netplans' },
                    { name: 'page one GmbH', value: 'pageone' },
                    { name: 'Paul Sonnabend Büro- und Datentechnik GmbH & Co. KG', value: 'sonnabend' },
                    { name: 'Schuster & Walther IT-Business GmbH', value: 'schuwa' },
                    { name: 'WIZARD Computersysteme GmbH', value: 'wizard' },
                ],
                default: '',
            },
            {
                displayName: 'Filter: Ticketqualität',
                name: 'ticketqualitart',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Gut', value: 'gut' },
                    { name: 'Mittelmäßig', value: 'mittelmaeßig' },
                    { name: 'Perfekt', value: 'perfekt' },
                    { name: 'Schlecht', value: 'schlecht' },
                ],
                default: '',
            },
            {
                displayName: 'Filter: E-Mail Text Anmeldung',
                name: 'e_mail_text_anmeldung',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Ja', value: 'Ja' },
                    { name: 'Nein', value: 'Nein' },
                ],
                default: '',
            },
            {
                displayName: 'Filter: KI-Ticket Infos vollständig',
                name: 'kiticketinfo',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Ja (alle Infos vorhanden)', value: 'Alle notwendigen Ticket Informationen' },
                    { name: 'Nein (Infos unvollständig)', value: 'Ticketinformationen nicht ausreichend für Bearbeitung' },
                ],
                default: '',
            },
            {
                displayName: 'Filter: Fonio Ticket',
                name: 'fonio_ticket',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Ja', value: 'Ja' },
                    { name: 'Nein', value: 'Nein' },
                ],
                default: '',
            },
            {
                displayName: 'Filter: KI-Priorisierung',
                name: 'ki_priorisierung',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Ja', value: 'true' },
                    { name: 'Nein', value: 'false' },
                ],
                default: '',
            },
            {
                displayName: 'Filter: KI-Training',
                name: 'ki_training',
                type: 'options',
                options: [
                    { name: '– kein Filter –', value: '' },
                    { name: 'Ja', value: 'true' },
                    { name: 'Nein', value: 'false' },
                ],
                default: '',
            },
        ],
    },

    // ─── CREATE ──────────────────────────────────────────────────────────────────
    {
        displayName: 'Titel',
        name: 'title',
        type: 'string',
        required: true,
        displayOptions: { show: { resource: ['ticket'], operation: ['create'] } },
        default: '',
        description: 'Betreff / Titel des Tickets',
    },
    {
        displayName: 'Gruppe',
        name: 'createGroup',
        type: 'options',
        typeOptions: { loadOptionsMethod: 'getGroups' },
        required: true,
        displayOptions: { show: { resource: ['ticket'], operation: ['create'] } },
        default: '',
        description: 'Zammad-Gruppe, der das Ticket zugeordnet wird',
    },
    {
        displayName: 'Kunden-E-Mail',
        name: 'customerEmail',
        type: 'string',
        required: true,
        displayOptions: { show: { resource: ['ticket'], operation: ['create'] } },
        default: '',
        placeholder: 'kunde@firma.de',
        description: 'E-Mail-Adresse des Kunden (Ersteller des Tickets)',
    },
    {
        displayName: 'Nachricht / Artikeltext',
        name: 'articleBody',
        type: 'string',
        required: true,
        typeOptions: { rows: 5 },
        displayOptions: { show: { resource: ['ticket'], operation: ['create'] } },
        default: '',
        description: 'Text des ersten Artikels (die eigentliche Ticketnachricht)',
    },
    {
        displayName: 'Weitere Felder',
        name: 'additionalFields',
        type: 'collection',
        placeholder: 'Feld hinzufügen',
        default: {},
        displayOptions: { show: { resource: ['ticket'], operation: ['create'] } },
        options: [
            {
                displayName: 'Status',
                name: 'state',
                type: 'options',
                options: [
                    { name: '01 Auftrag erfasst', value: '01 Auftrag erfasst' },
                    { name: '01.5 An Zuständigen weitergegeben', value: '01.5 An Zuständigen weitergegeben' },
                    { name: '02 in Bearbeitung', value: '02 in Bearbeitung' },
                    { name: '03 Unterbrochen', value: '03 Unterbrochen' },
                    { name: '04 geschlossen', value: '04 geschlossen' },
                    { name: '04 geschlossen (ohne Meldung)', value: '04 geschlossen (ohne Meldung)' },
                    { name: 'Abholung beauftragt', value: 'Abholung beauftragt' },
                    { name: 'Angebot Vertrieb', value: 'Angebot Vertrieb' },
                    { name: 'Datenverarbeitung (Zählerstände)', value: 'Datenverarbeitung (Zählerstände)' },
                    { name: 'fürs Order Team', value: 'fürs Order Team' },
                    { name: 'in Entwicklung', value: 'in Entwicklung' },
                    { name: 'Infos fehlen', value: 'Infos fehlen' },
                    { name: 'KVA erstellt', value: 'KVA erstellt' },
                    { name: 'open', value: 'open' },
                    { name: 'pending close', value: 'pending close' },
                    { name: 'Service (Extern)', value: 'Service (Extern)' },
                    { name: 'Techniker geplant', value: 'Techniker geplant' },
                    { name: 'Termin vereinbart', value: 'Termin vereinbart' },
                    { name: 'Ticket berechnen', value: 'Ticket berechnen' },
                    { name: 'Warte auf Rückmeldung', value: 'Warte auf Rückmeldung' },
                    { name: 'warten auf Schließen (ohne Meldung)', value: 'warten auf Schließen (ohne Meldung)' },
                    { name: 'Zammad KI', value: 'Zammad KI' },
                ],
                default: '01 Auftrag erfasst',
            },
            {
                displayName: 'Priorität',
                name: 'priority',
                type: 'options',
                options: [
                    { name: 'Niedrig', value: 'Niedrig' },
                    { name: 'Normal', value: 'Normal' },
                    { name: 'Hoch', value: 'Hoch' },
                    { name: 'ShowStopper', value: 'ShowStopper' },
                    { name: 'Techniker vor Ort', value: 'Techniker vor Ort' },
                ],
                default: 'Normal',
            },
            {
                displayName: 'Owner (Agent-Login)',
                name: 'owner',
                type: 'string',
                default: '',
                description: 'Login-Name des zugewiesenen Agenten',
            },
            {
                displayName: 'Artikel-Betreff',
                name: 'articleSubject',
                type: 'string',
                default: '',
                description: 'Betreff des ersten Artikels (Standard: Tickettitel)',
            },
            {
                displayName: 'Artikel-Typ',
                name: 'articleType',
                type: 'options',
                options: [
                    { name: 'Notiz', value: 'note' },
                    { name: 'E-Mail', value: 'email' },
                    { name: 'Telefon', value: 'phone' },
                    { name: 'Web', value: 'web' },
                ],
                default: 'note',
            },
            {
                displayName: 'Inhaltstyp',
                name: 'contentType',
                type: 'options',
                options: [
                    { name: 'Klartext (text/plain)', value: 'text/plain' },
                    { name: 'HTML (text/html)', value: 'text/html' },
                ],
                default: 'text/plain',
            },
            {
                displayName: 'Interne Notiz',
                name: 'internal',
                type: 'boolean',
                default: false,
                description: 'Wenn aktiv, ist der Artikel nur für Agenten sichtbar',
            },
            ...ticketCustomFields,
        ],
    },
    {
        displayName: 'Weitere Custom Fields',
        name: 'customFields',
        type: 'fixedCollection',
        typeOptions: { multipleValues: true },
        placeholder: 'Custom Field hinzufügen',
        default: {},
        displayOptions: { show: { resource: ['ticket'], operation: ['create'] } },
        description: 'Für Custom Fields, die oben nicht aufgeführt sind (Feldname exakt wie in Zammad konfiguriert)',
        options: [
            {
                name: 'fields',
                displayName: 'Feld',
                values: [
                    {
                        displayName: 'Feldname',
                        name: 'name',
                        type: 'string',
                        default: '',
                        placeholder: 'z. B. custom_dropdown',
                    },
                    {
                        displayName: 'Wert',
                        name: 'value',
                        type: 'string',
                        default: '',
                    },
                ],
            },
        ],
    },

    // ─── UPDATE ──────────────────────────────────────────────────────────────────
    {
        displayName: 'Zu aktualisierende Felder',
        name: 'updateFields',
        type: 'collection',
        placeholder: 'Feld hinzufügen',
        default: {},
        displayOptions: { show: { resource: ['ticket'], operation: ['update'] } },
        options: [
            {
                displayName: 'Titel',
                name: 'title',
                type: 'string',
                default: '',
            },
            {
                displayName: 'Gruppe',
                name: 'group',
                type: 'options',
                typeOptions: { loadOptionsMethod: 'getGroups' },
                default: '',
            },
            {
                displayName: 'Status',
                name: 'state',
                type: 'options',
                options: [
                    { name: '01 Auftrag erfasst', value: '01 Auftrag erfasst' },
                    { name: '01.5 An Zuständigen weitergegeben', value: '01.5 An Zuständigen weitergegeben' },
                    { name: '02 in Bearbeitung', value: '02 in Bearbeitung' },
                    { name: '03 Unterbrochen', value: '03 Unterbrochen' },
                    { name: '04 geschlossen', value: '04 geschlossen' },
                    { name: '04 geschlossen (ohne Meldung)', value: '04 geschlossen (ohne Meldung)' },
                    { name: 'Abholung beauftragt', value: 'Abholung beauftragt' },
                    { name: 'Angebot Vertrieb', value: 'Angebot Vertrieb' },
                    { name: 'Datenverarbeitung (Zählerstände)', value: 'Datenverarbeitung (Zählerstände)' },
                    { name: 'fürs Order Team', value: 'fürs Order Team' },
                    { name: 'in Entwicklung', value: 'in Entwicklung' },
                    { name: 'Infos fehlen', value: 'Infos fehlen' },
                    { name: 'KVA erstellt', value: 'KVA erstellt' },
                    { name: 'open', value: 'open' },
                    { name: 'pending close', value: 'pending close' },
                    { name: 'Service (Extern)', value: 'Service (Extern)' },
                    { name: 'Techniker geplant', value: 'Techniker geplant' },
                    { name: 'Termin vereinbart', value: 'Termin vereinbart' },
                    { name: 'Ticket berechnen', value: 'Ticket berechnen' },
                    { name: 'Warte auf Rückmeldung', value: 'Warte auf Rückmeldung' },
                    { name: 'warten auf Schließen (ohne Meldung)', value: 'warten auf Schließen (ohne Meldung)' },
                    { name: 'Zammad KI', value: 'Zammad KI' },
                ],
                default: 'open',
            },
            {
                displayName: 'Priorität',
                name: 'priority',
                type: 'options',
                options: [
                    { name: 'Niedrig', value: 'Niedrig' },
                    { name: 'Normal', value: 'Normal' },
                    { name: 'Hoch', value: 'Hoch' },
                    { name: 'ShowStopper', value: 'ShowStopper' },
                    { name: 'Techniker vor Ort', value: 'Techniker vor Ort' },
                ],
                default: 'Normal',
            },
            {
                displayName: 'Owner (Agent-Login)',
                name: 'owner',
                type: 'string',
                default: '',
            },
            {
                displayName: 'Kunde (E-Mail)',
                name: 'customer',
                type: 'string',
                default: '',
            },
            {
                displayName: 'Notiz',
                name: 'note',
                type: 'string',
                typeOptions: { rows: 4 },
                default: '',
                description: 'Fügt dem Ticket einen internen Kommentar (Notiz) hinzu',
            },
            {
                displayName: 'Notiz öffentlich',
                name: 'noteInternal',
                type: 'boolean',
                default: false,
                description: 'Whether die Notiz intern (nur Agenten) oder öffentlich (für Kunden sichtbar) ist',
            },
            ...ticketCustomFields,
        ],
    },
    {
        displayName: 'Weitere Custom Fields',
        name: 'customFields',
        type: 'fixedCollection',
        typeOptions: { multipleValues: true },
        placeholder: 'Custom Field hinzufügen',
        default: {},
        displayOptions: { show: { resource: ['ticket'], operation: ['update'] } },
        description: 'Für Custom Fields, die oben nicht aufgeführt sind (Feldname exakt wie in Zammad konfiguriert)',
        options: [
            {
                name: 'fields',
                displayName: 'Feld',
                values: [
                    {
                        displayName: 'Feldname',
                        name: 'name',
                        type: 'string',
                        default: '',
                        placeholder: 'z. B. custom_dropdown',
                        description: 'API-Name des Custom Fields in Zammad (über Custom API Call → /api/v1/object_manager_attributes?object=Ticket ermittelbar)',
                    },
                    {
                        displayName: 'Wert',
                        name: 'value',
                        type: 'string',
                        default: '',
                    },
                ],
            },
        ],
    },
];
